### ISSUE TITLE
[experimental] MCS Service Discovery

### ISSUE THREAD

**Issue by nmittler** [istio/enhancements#72]
Enhancement Description
This adds the capability in Istio to control the discoverability of the services based on MCS service exports.

User Story
Istio is deployed with the feature enabled, which will make services cluster-local by default. Service owner can push a ServiceExport CR to a cluster, which will configure Istio to allow the endpoints in the cluster for that service to be accessible across the mesh.

Proposal
[design doc](https://docs.google.com/document/d/125JiDxXjvqHXu_678mUXKy3pKOvfSw4zKwXJjulU_ug/edit)

Impacted Working Groups
* Networking
* Environments

**Comment by brian-avery** [comment]
@nmittler Can you please open a PR to add this? A file should be created in https://github.com/istio/enhancements/tree/master/features and https://github.com/istio/enhancements/blob/master/features.yaml should be updated with the feature.

**Comment by nmittler** [comment]
@brian-avery will do. Can you update the top-level MD file to reflect the process?

**Comment by nmittler** [comment]
Ah, looks like you already did this for MCS: https://github.com/istio/enhancements/blob/master/features/Kubernetes_MCS.md

**Comment by brian-avery** [comment]
Those actually link to: 
https://github.com/istio/enhancements/blob/master/features/insert_your_link_here
and
https://github.com/istio/enhancements/blob/master/features/insert_your_link_here

For you to fill in pointing to where ever you put your instructions. 

Some docs that Steve added here (directly from the file, just not shown unless you edit or view raw): 

**User stories**
[//]: # (User stories are a way to communicate user value. User stories follow the style)
[//]: # (as a [type of user], I want [an action] so that [a benefit/a value]. Istio currently has no user)
[//]: # (story template. Maybe you can make one?)

[//]: # (User stories must be presented in a work group meeting. They need no approval and are later integrated)
[//]: # (into the RFCs, which do need approval for alpha. You may find value to negotiate within the work group where the)
[//]: # (user stories are presented to help clarify the user stories.)

**Feedback Plan**
[//]: # (This may include user feedback meetings, discuss.istio.io conversations, GitHub issues, or mailing lists.)


Informal, just trying to make sure there's a documented idea of what it's trying to accomplish and what the plan is for getting feedback.

**Comment by nmittler** [comment]
@brian-avery thanks. I'll close this PR and open a new one to update the existing MD file.
